/**
 * Copyright (c) 2017-2019, NVIDIA CORPORATION.  All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef __ROS2_DEEPSTREAM_GST_DS_RCLCPP_PUBLISHER_H__
#define __ROS2_DEEPSTREAM_GST_DS_RCLCPP_PUBLISHER_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <memory>
#include "rclcpp/rclcpp.hpp"
#include "ros2_deepstream_msgs/msg/nv_ds_meta_data.hpp"

/* Open CV headers */
// #include "opencv2/imgproc/imgproc.hpp"
// #include "opencv2/highgui/highgui.hpp"

#include <cuda.h>
#include <cuda_runtime.h>
#include "nvbufsurface.h"
#include "nvbufsurftransform.h"
#include "gst-nvquery.h"
#include "gstnvdsmeta.h"
// #include "dsexample_lib/dsexample_lib.h"

/* Package and library details required for plugin_init */
#define PACKAGE "ds_rclcpp_publisher"
#define VERSION "1.0"
#define LICENSE "LGPL"
#define DESCRIPTION "Publish NVDS meta data to a ROS 2 topic"
#define BINARY_PACKAGE "Publish NVDS meta data to a ROS 2 topic"
#define URL "https://github.com/brawner/ros2_deepstream"


G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDsRclcppPublisher GstDsRclcppPublisher;
typedef struct _GstDsRclcppPublisherClass GstDsRclcppPublisherClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DS_RCLCPP_PUBLISHER (gst_ds_rclcpp_publisher_get_type())
#define GST_DS_RCLCPP_PUBLISHER(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_DS_RCLCPP_PUBLISHER,GstDsRclcppPublisher))
#define GST_DS_RCLCPP_PUBLISHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_DS_RCLCPP_PUBLISHER,GstDsRclcppPublisherClass))
#define GST_DS_RCLCPP_PUBLISHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DS_RCLCPP_PUBLISHER, GstDsRclcppPublisherClass))
#define GST_IS_DS_RCLCPP_PUBLISHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_DS_RCLCPP_PUBLISHER))
#define GST_IS_DS_RCLCPP_PUBLISHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_DS_RCLCPP_PUBLISHER))
#define GST_DS_RCLCPP_PUBLISHER_CAST(obj)  ((GstDsRclcppPublisher *)(obj))

class GstDsRclcppPublisherNode : public rclcpp::Node {
public:
  GstDsRclcppPublisherNode(const std::string& name, const std::string& topic_name);
  ~GstDsRclcppPublisherNode();

  static void ProcessNewFrame(GstDsRclcppPublisherNode* node, const NvDsFrameMeta* data);

  void Publish(ros2_deepstream_msgs::msg::NvDsMetaData::UniquePtr msg);
  std::shared_ptr<rclcpp::Publisher<ros2_deepstream_msgs::msg::NvDsMetaData>> publisher_;
};

struct _GstDsRclcppPublisher
{
  GstBaseTransform base_trans;

  std::unique_ptr<GstDsRclcppPublisherNode> node;

  // Context of the custom algorithm library
  // DsExampleCtx *dsexamplelib_ctx;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Frame number of the current input buffer
  guint64 frame_num;

  // CUDA Stream used for allocating the CUDA task
  cudaStream_t cuda_stream;

  // Host buffer to store RGB data for use by algorithm
  void *host_rgb_buf;

  // the intermediate scratch buffer for conversions RGBA
  NvBufSurface *inter_buf;

  // OpenCV mat containing RGB data
  // cv::Mat *cvmat;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  // Resolution at which frames/objects should be processed
  gint processing_width;
  gint processing_height;

  // Amount of objects processed in single call to algorithm
  guint batch_size;

  // GPU ID on which we expect to execute the task
  guint gpu_id;

  // Boolean indicating if entire frame or cropped objects should be processed
  gboolean process_full_frame;
};

// Boiler plate stuff
struct _GstDsRclcppPublisherClass
{
  GstBaseTransformClass parent_class;
};

GType gst_ds_rclcpp_publisher_get_type (void);

G_END_DECLS
#endif /* __ROS2_DEEPSTREAM_GST_DS_RCLCPP_PUBLISHER_H__ */
